# -*- coding: utf-8 -*-
"""Important Math Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xOLgRzoaDfhfybUgskzswm2d4eWLPxk
"""

def slidingWindowAvg(data, windowLen):
  holderList = []
  for i in range(0, len(data) - windowLen + 1):

    holderList.append(sum(data[i:windowLen]) / (windowLen - i))
    windowLen += 1

  return holderList

print(slidingWindowAvg([13, 26, 30, 1, 5, 9, 17, 50], 3))

def weightedAvg(data, weights):

  return sum([a * b for a, b in list(zip(data, weights))]) / sum(weights)

d = [1,2,3,4]
w = [6,7,-1,3]

print(weightedAvg(d, w))

def encodeEvenOdd(data):

  for i in range(len(data)):

    if data[i] % 2 == 0:
      data[i] = 'E'

    elif data[i] % 2 == 1:
      data[i] = 'O'

  return data

print(encodeEvenOdd([20, 43, 1, 9, 8]))

a = [1,2,3,4,5]

b = list(map(str, a))
b
